server.port: 8888

security.basic.enabled: false


spring:
  cloud:
    config:
      server:
        native:
          search-locations: file:/var/shared
  profiles:
     active: native

spring.rabbitmq:
  host: localhost
  port: 5672

logging:
  level:
    root: INFO
    demo: INFO

    org.springframework.amqp.rabbit.listener.BlockingQueueConsumer: INFO
    org.apache.catalina.session.ManagerBase: INFO

    # Set INFO to see the allocated port
    org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer: INFO
    org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainer: INFO


---
# For deployment in Docker containers
spring:
  profiles: docker

spring.rabbitmq.host: rabbitmq

# when running docker locally on a dev pc the config-repo is mounted to a local git-repo in docker-compose file
spring.cloud.config.server.git.uri: /config-repo



